# Generated by Django 4.2.1 on 2023-07-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dseires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire', models.CharField(max_length=255)),
                ('type_reg', models.CharField(choices=[('عام', 'عام'), ('موازي', 'موازي')], max_length=20)),
                ('number_of_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students_University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('average', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Average')),
                ('exam', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='National examination score')),
                ('final_average', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Final Average')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InformationStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='أدخل الاسم الثلاثي', max_length=255)),
                ('final_average', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Final Average')),
                ('photo', models.ImageField(blank=True, help_text='أدخل صورة مصدقة عن وثيقة التخرج', null=True, upload_to='images')),
                ('master_entrance_photo', models.ImageField(blank=True, help_text='أدخل صورة مصدقة عن امتحان قيد الماجستير', null=True, upload_to='images')),
                ('nonworking_document_photo', models.ImageField(blank=True, help_text='صورة عن وثيقة غير عامل أو موافقة الجهة التي يعمل لديها الطالب', null=True, upload_to='images')),
                ('payment_receipt_photo', models.ImageField(blank=True, help_text='صورة عن إيصال دفع خاص بطلاب الموازي', null=True, upload_to='images')),
                ('desires', models.ManyToManyField(related_name='student_desire', to='application.dseires')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='application.students_university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informationstudent', to='accounts.student')),
            ],
            options={
                'ordering': ['-final_average'],
            },
        ),
        migrations.AddField(
            model_name='dseires',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_name', to='application.university'),
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='accounts.student')),
            ],
        ),
    ]
