# Generated by Django 4.2.1 on 2023-07-22 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationstudent',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
