# Generated by Django 4.2.1 on 2023-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_informationstudent_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationstudent',
            name='id_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
