# Generated by Django 4.2.1 on 2023-07-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_students_university_final_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_university',
            name='final_average',
        ),
    ]
