# Generated by Django 4.2.1 on 2023-08-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_students_university_final_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationstudent',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
